# Generated by Django 3.2.25 on 2024-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.TextField()),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
